frontend:
  service:
    type: NodePort
  image:
    repository: asia-northeast3-docker.pkg.dev/project-62b51d1b-b1c4-4053-bb0/photo-storage/photo-storage-frontend
    tag: latest
    pullPolicy: IfNotPresent

backend:
  healthCheck:
    enabled: true
    path: /actuator/health
  
  service:
    type: NodePort
  
  serviceAccount:
    create: true
    name: photo-storage-backend
    annotations:
      iam.gke.io/gcp-service-account: photo-storage-backend@project-62b51d1b-b1c4-4053-bb0.iam.gserviceaccount.com

  awsWorkloadIdentity:
    enabled: true
    roleArn: arn:aws:iam::022868553365:role/photo-storage-gcp-backend-s3-role
    region: ap-northeast-2
    audience: sts.amazonaws.com


  image:
    repository: asia-northeast3-docker.pkg.dev/project-62b51d1b-b1c4-4053-bb0/photo-storage/photo-storage-backend
    tag: latest
    pullPolicy: IfNotPresent

  env:
    cloudProvider: gcp
    storageProvider: gcs
    replicationEnabled: true
    replicationTargetProvider: s3
    gcsBucketName: project-62b51d1b-b1c4-4053-bb0-photo-storage-bucket
    s3BucketName: photo-storage-bucket-dev-lty02
    frontendUrl: https://photo-storage.example.com
    datasourceUrl: jdbc:postgresql://photo-storage-db.cr000kkwg7nd.ap-northeast-2.rds.amazonaws.com:5432/photo_storage
    datasourceUsername: photo_user
    datasourcePassword: ""

ingress:
  enabled: true
  className: ""
  host: ""
  annotations:
    kubernetes.io/ingress.class: gce
