frontend:
  image:
    repository: 022868553365.dkr.ecr.ap-northeast-2.amazonaws.com/photo-storage-frontend
    tag: latest
    pullPolicy: IfNotPresent

backend:
  serviceAccount:
    create: true
    name: photo-storage-backend
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::022868553365:role/photo-storage-backend-irsa-role

  gcpWorkloadIdentity:
    enabled: true
    projectNumber: "1079817536617"
    poolId: photo-storage-aws-eks
    providerId: photo-storage-eks
    serviceAccountEmail: photo-storage-backend@project-62b51d1b-b1c4-4053-bb0.iam.gserviceaccount.com

  image:
    repository: 022868553365.dkr.ecr.ap-northeast-2.amazonaws.com/photo-storage-backend
    tag: latest
    pullPolicy: IfNotPresent

  env:
    cloudProvider: aws
    storageProvider: s3
    replicationEnabled: true
    replicationTargetProvider: gcs
    s3BucketName: photo-storage-bucket-dev-lty02
    gcsBucketName: project-62b51d1b-b1c4-4053-bb0-photo-storage-bucket
    frontendUrl: https://photo-storage.example.com
    datasourceUrl: jdbc:postgresql://photo-storage-db.cr000kkwg7nd.ap-northeast-2.rds.amazonaws.com:5432/photo_storage
    datasourceUsername: photo_user
    datasourcePassword: ""
    

ingress:
  enabled: true
  className: alb
  host: ""
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
