frontend:
  image:
    repository: YOUR_AWS_ACCOUNT_ID.dkr.ecr.ap-northeast-2.amazonaws.com/photo-storage-frontend
    tag: nginx-fix-1
    pullPolicy: IfNotPresent

backend:
  serviceAccount:
    create: true
    name: photo-storage-backend
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::YOUR_AWS_ACCOUNT_ID:role/photo-storage-backend-irsa-role

  image:
    repository: YOUR_AWS_ACCOUNT_ID.dkr.ecr.ap-northeast-2.amazonaws.com/photo-storage-backend
    tag: irsa-fix-1
    pullPolicy: IfNotPresent

  env:
    cloudProvider: aws
    storageProvider: s3
    replicationEnabled: true
    replicationTargetProvider: gcs
    s3BucketName: YOUR_S3_BUCKET_NAME
    gcsBucketName: YOUR_GCS_BUCKET_NAME
    frontendUrl: https://photo-storage.example.com
    datasourceUrl: jdbc:postgresql://YOUR_DATABASE_HOST:5432/photo_storage
    datasourceUsername: photo_user
    datasourcePassword: ""
    

ingress:
  enabled: true
  className: alb
  host: ""
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
