frontend:
  service:
    type: NodePort
  image:
    repository: asia-northeast3-docker.pkg.dev/YOUR_GCP_PROJECT_ID/photo-storage/photo-storage-frontend
    tag: latest
    pullPolicy: IfNotPresent

backend:
  healthCheck:
    enabled: true
    path: /actuator/health
  
  service:
    type: NodePort
  
  serviceAccount:
    create: true
    name: photo-storage-backend
    annotations:
      iam.gke.io/gcp-service-account: photo-storage-backend@YOUR_GCP_PROJECT_ID.iam.gserviceaccount.com

  awsWorkloadIdentity:
    enabled: true
    roleArn: arn:aws:iam::YOUR_AWS_ACCOUNT_ID:role/photo-storage-gcp-backend-s3-role
    region: ap-northeast-2
    audience: sts.amazonaws.com


  image:
    repository: asia-northeast3-docker.pkg.dev/YOUR_GCP_PROJECT_ID/photo-storage/photo-storage-backend
    tag: latest
    pullPolicy: IfNotPresent

  env:
    cloudProvider: gcp
    storageProvider: gcs
    replicationEnabled: true
    replicationTargetProvider: s3
    gcsBucketName: YOUR_GCS_BUCKET_NAME
    s3BucketName: YOUR_S3_BUCKET_NAME
    frontendUrl: https://photo-storage.example.com
    datasourceUrl: jdbc:postgresql://YOUR_DATABASE_HOST:5432/photo_storage
    datasourceUsername: photo_user
    datasourcePassword: ""

ingress:
  enabled: true
  className: ""
  host: ""
  annotations:
    kubernetes.io/ingress.class: gce
