apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
  {{- if .Values.backend.healthCheck.enabled }}
  annotations:
    cloud.google.com/backend-config: '{"ports":{"{{ .Values.backend.service.port }}":"{{ .Release.Name }}-backend-config"}}'
  {{- end }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: {{ .Release.Name }}-backend
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
