apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    app: {{ .Release.Name }}-backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend
    spec:
      serviceAccountName: {{ .Values.backend.serviceAccount.name }}
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.service.port }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            {{ if .Values.backend.gcpWorkloadIdentity.enabled }}
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/run/gcp/credentials.json
            {{ end }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
            - secretRef:
                name: {{ .Release.Name }}-secret
          {{ if .Values.backend.gcpWorkloadIdentity.enabled }}
          volumeMounts:
            - name: gcp-token
              mountPath: /var/run/gcp/token
              subPath: token
              readOnly: true
            - name: gcp-credentials
              mountPath: /var/run/gcp/credentials.json
              subPath: credentials.json
              readOnly: true
          {{ end }}
      {{ if .Values.backend.gcpWorkloadIdentity.enabled }}
      volumes:
        - name: gcp-token
          projected:
            sources:
              - serviceAccountToken:
                  path: token
                  audience: {{ printf "https://iam.googleapis.com/projects/%s/locations/global/workloadIdentityPools/%s/providers/%s" .Values.backend.gcpWorkloadIdentity.projectNumber .Values.backend.gcpWorkloadIdentity.poolId .Values.backend.gcpWorkloadIdentity.providerId | quote }}
                  expirationSeconds: 3600
        - name: gcp-credentials
          configMap:
            name: {{ .Release.Name }}-gcp-credentials
      {{ end }}
