{{- if .Values.backend.gcpWorkloadIdentity.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-gcp-credentials
data:
  credentials.json: |
    {
      "type": "external_account",
      "audience": "//iam.googleapis.com/projects/{{ .Values.backend.gcpWorkloadIdentity.projectNumber }}/locations/global/workloadIdentityPools/{{ .Values.backend.gcpWorkloadIdentity.poolId }}/providers/{{ .Values.backend.gcpWorkloadIdentity.providerId }}",
      "subject_token_type": "urn:ietf:params:oauth:token-type:jwt",
      "token_url": "https://sts.googleapis.com/v1/token",
      "service_account_impersonation_url": "https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/{{ .Values.backend.gcpWorkloadIdentity.serviceAccountEmail }}:generateAccessToken",
      "credential_source": {
        "file": "/var/run/gcp/token",
        "format": {
          "type": "text"
        }
      }
    }
{{- end }}
