apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: {{ .Values.backend.env.datasourceUrl | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.backend.env.datasourceUsername | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.backend.env.datasourcePassword | quote }}
