{{- if .Values.backend.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.backend.serviceAccount.name }}
  annotations:
    {{- toYaml .Values.backend.serviceAccount.annotations | nindent 4 }}
{{- end }}